baseURL = "http://example.org/"
languageCode = "en-us"
<<<<<<< HEAD
title = "weili108 New Hugo Site"
theme = "ananke"
=======
title = "weili108's Hugo Site"
theme = "ananke"

>>>>>>> bacfda7c34baf57338310cdd125ac1a99e30bc85
